import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import NextTopLoader from 'nextjs-toploader';

import { Toaster } from "@/components/ui/sonner"
import Navbar from "@/components/navbar";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <NextTopLoader
          color="#2299DD"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={true}
          easing="ease"
          speed={200}
          shadow="0 0 10px #2299DD,0 0 5px #2299DD"
          template="linear-gradient(to right, #2299DD, #2299DD)"
          zIndex={1600}
          showAtBottom={false}
        />

        <Navbar />
        <Toaster />
        {children}
      </body>
    </html>
  );
}